// こういう対応表とか作ってくれるチャッピー君神過ぎる。

export const continentCodeMap = {
    "AF": "アフリカ",
    "AN": "南極大陸",
    "AS": "アジア",
    "EU": "ヨーロッパ",
    "NA": "北アメリカ",
    "SA": "南アメリカ",
    "OC": "オセアニア"
};

export const countryMap = {
    "Japan": "日本",
    "United States": "アメリカ",
    "United Kingdom": "イギリス",
    "China": "中国",
    "South Korea": "韓国",
    "France": "フランス",
    "Germany": "ドイツ",
    "Italy": "イタリア",
    "Canada": "カナダ",
    "Australia": "オーストラリア",
    "Brazil": "ブラジル",
    "Russia": "ロシア",
    "India": "インド",
    "Mexico": "メキシコ",
    "Spain": "スペイン",
    "Netherlands": "オランダ",
    "Sweden": "スウェーデン",
    "Norway": "ノルウェー",
    "Finland": "フィンランド",
    "Denmark": "デンマーク",
    "Belgium": "ベルギー",
    "Switzerland": "スイス",
    "Austria": "オーストリア",
    "Portugal": "ポルトガル",
    "Ireland": "アイルランド",
    "New Zealand": "ニュージーランド",
    "Thailand": "タイ",
    "Vietnam": "ベトナム",
    "Malaysia": "マレーシア",
    "Singapore": "シンガポール",
    "Indonesia": "インドネシア",
    "Philippines": "フィリピン",
    "Turkey": "トルコ",
    "Saudi Arabia": "サウジアラビア",
    "Egypt": "エジプト",
    "South Africa": "南アフリカ",
    "Argentina": "アルゼンチン",
    "Chile": "チリ",
    "Colombia": "コロンビア",
    "Peru": "ペルー",
    "Poland": "ポーランド",
    "Czech Republic": "チェコ",
    "Greece": "ギリシャ",
    "Hungary": "ハンガリー",
    "Romania": "ルーマニア"
};

export const countryCapitalMap = {
    "Tokyo": "東京",
    "Ottawa": "オタワ",
    "Washington": "ワシントン",
    "London": "ロンドン",
    "Paris": "パリ",
    "Berlin": "ベルリン",
    "Rome": "ローマ",
    "Madrid": "マドリード",
    "Lisbon": "リスボン",
    "Amsterdam": "アムステルダム",
    "Brussels": "ブリュッセル",
    "Bern": "ベルン",
    "Vienna": "ウィーン",
    "Prague": "プラハ",
    "Budapest": "ブダペスト",
    "Warsaw": "ワルシャワ",
    "Moscow": "モスクワ",
    "Kyiv": "キエフ／キーウ",
    "Minsk": "ミンスク",
    "Istanbul": "イスタンブール",
    "Ankara": "アンカラ",
    "Athens": "アテネ",
    "Sofia": "ソフィア",
    "Bucharest": "ブカレスト",
    "Belgrade": "ベオグラード",
    "Zagreb": "ザグレブ",
    "Sarajevo": "サラエボ",
    "Skopje": "スコピエ",
    "Reykjavik": "レイキャヴィク",
    "Oslo": "オスロ",
    "Stockholm": "ストックホルム",
    "Helsinki": "ヘルシンキ",
    "Copenhagen": "コペンハーゲン",
    "Dublin": "ダブリン",
    "Bern": "ベルン",
    "Bratislava": "ブラチスラヴァ",
    "Vatican City": "バチカン市国",
    "Andorra la Vella": "アンドラ・ラ・ヴェリャ",
    "San Marino": "サンマリノ",
    "Valletta": "ヴァレッタ",
    "Riga": "リーガ",
    "Vilnius": "ヴィリニュス",
    "Tallinn": "タリン",
    "Minsk": "ミンスク",
    "Beijing": "北京",
    "Shanghai": "（注：正式な首都は）北京",
    "Seoul": "ソウル",
    "Pyongyang": "平壌",
    "New Delhi": "ニューデリー",
    "Islamabad": "イスラマバード",
    "Dhaka": "ダッカ",
    "Kathmandu": "カトマンズ",
    "Thimphu": "ティンプー",
    "Colombo": "コロンボ",
    "Male": "マーレ",
    "Jakarta": "ジャカルタ",
    "Kuala Lumpur": "クアラルンプール",
    "Singapore": "シンガポール",
    "Manila": "マニラ",
    "Bangkok": "バンコク",
    "Hanoi": "ハノイ",
    "Vientiane": "ヴィエンチャン",
    "Phnom Penh": "プノンペン",
    "Canberra": "キャンベラ",
    "Wellington": "ウェリントン",
    "Suva": "スバ",
    "Port Moresby": "ポートモレスビー",
    "Ngerulmud": "ンゲルムド",
    "Male": "マーレ",
    "Honiara": "ホニアラ",
    "Port Vila": "ポートビラ",
    "Apia": "アピア",
    "Palikir": "パリキール",
    "Melekeok": "メレケオク",
    "Beirut": "ベイルート",
    "Amman": "アンマン",
    "Jerusalem": "エルサレム",
    "Ramallah": "ラマッラ（政府所在地・場合により）",
    "Riyadh": "リヤド",
    "Abu Dhabi": "アブダビ",
    "Doha": "ドーハ",
    "Kuwait City": "クウェートシティ",
    "Manama": "マナーマ",
    "Muscat": "マスカット",
    "Sana'a": "サヌア（サナア）",
    "Tehran": "テヘラン",
    "Baghdad": "バグダード",
    "Damascus": "ダマスカス",
    "Jerusalem": "エルサレム",
    "Cairo": "カイロ",
    "Tripoli": "トリポリ",
    "Tunis": "チュニス",
    "Algiers": "アルジェ",
    "Rabat": "ラバト",
    "Khartoum": "ハルツーム",
    "Nairobi": "ナイロビ",
    "Kampala": "カンパラ",
    "Kigali": "キガリ",
    "Kigali": "キガリ",
    "Kigali": "キガリ",
    "Dar es Salaam": "ダーエスサラーム（行政中心）",
    "Dodoma": "ドドマ",
    "Addis Ababa": "アディスアベバ",
    "Accra": "アクラ",
    "Abuja": "アブジャ",
    "Yaounde": "ヤウンデ",
    "Libreville": "リーブルヴィル",
    "Kinshasa": "キンシャサ",
    "Brazzaville": "ブラザヴィル",
    "Lagos": "（注：ナイジェリアの首都はアブジャ）",
    "Brasília": "ブラジリア",
    "Buenos Aires": "ブエノスアイレス",
    "Santiago": "サンティアゴ",
    "Lima": "リマ",
    "Bogotá": "ボゴタ",
    "Caracas": "カラカス",
    "Quito": "キト",
    "La Paz": "ラパス",
    "Sucre": "スクレ",
    "Asunción": "アスンシオン",
    "Montevideo": "モンテビデオ",
    "San José": "サンホセ",
    "Panama City": "パナマシティ",
    "Havana": "ハバナ",
    "Santo Domingo": "サントドミンゴ",
    "Kingston": "キングストン",
    "Nassau": "ナッソー",
    "Flying": "（注：例外・特殊ケース）"
};

export const regionMap = {
    // 日本
    "Hokkaido": "北海道",
    "Aomori": "青森県",
    "Iwate": "岩手県",
    "Miyagi": "宮城県",
    "Akita": "秋田県",
    "Yamagata": "山形県",
    "Fukushima": "福島県",
    "Ibaraki": "茨城県",
    "Tochigi": "栃木県",
    "Gunma": "群馬県",
    "Saitama": "埼玉県",
    "Chiba": "千葉県",
    "Tokyo": "東京都",
    "Kanagawa": "神奈川県",
    "Niigata": "新潟県",
    "Toyama": "富山県",
    "Ishikawa": "石川県",
    "Fukui": "福井県",
    "Yamanashi": "山梨県",
    "Nagano": "長野県",
    "Gifu": "岐阜県",
    "Shizuoka": "静岡県",
    "Aichi": "愛知県",
    "Mie": "三重県",
    "Shiga": "滋賀県",
    "Kyoto": "京都府",
    "Osaka": "大阪府",
    "Hyogo": "兵庫県",
    "Nara": "奈良県",
    "Wakayama": "和歌山県",
    "Tottori": "鳥取県",
    "Shimane": "島根県",
    "Okayama": "岡山県",
    "Hiroshima": "広島県",
    "Yamaguchi": "山口県",
    "Tokushima": "徳島県",
    "Kagawa": "香川県",
    "Ehime": "愛媛県",
    "Kochi": "高知県",
    "Fukuoka": "福岡県",
    "Saga": "佐賀県",
    "Nagasaki": "長崎県",
    "Kumamoto": "熊本県",
    "Oita": "大分県",
    "Miyazaki": "宮崎県",
    "Kagoshima": "鹿児島県",
    "Okinawa": "沖縄県",

    // アメリカ 50州
    "Alabama": "アラバマ州",
    "Alaska": "アラスカ州",
    "Arizona": "アリゾナ州",
    "Arkansas": "アーカンソー州",
    "California": "カリフォルニア州",
    "Colorado": "コロラド州",
    "Connecticut": "コネチカット州",
    "Delaware": "デラウェア州",
    "Florida": "フロリダ州",
    "Georgia": "ジョージア州",
    "Hawaii": "ハワイ州",
    "Idaho": "アイダホ州",
    "Illinois": "イリノイ州",
    "Indiana": "インディアナ州",
    "Iowa": "アイオワ州",
    "Kansas": "カンザス州",
    "Kentucky": "ケンタッキー州",
    "Louisiana": "ルイジアナ州",
    "Maine": "メイン州",
    "Maryland": "メリーランド州",
    "Massachusetts": "マサチューセッツ州",
    "Michigan": "ミシガン州",
    "Minnesota": "ミネソタ州",
    "Mississippi": "ミシシッピ州",
    "Missouri": "ミズーリ州",
    "Montana": "モンタナ州",
    "Nebraska": "ネブラスカ州",
    "Nevada": "ネバダ州",
    "New Hampshire": "ニューハンプシャー州",
    "New Jersey": "ニュージャージー州",
    "New Mexico": "ニューメキシコ州",
    "New York": "ニューヨーク州",
    "North Carolina": "ノースカロライナ州",
    "North Dakota": "ノースダコタ州",
    "Ohio": "オハイオ州",
    "Oklahoma": "オクラホマ州",
    "Oregon": "オレゴン州",
    "Pennsylvania": "ペンシルベニア州",
    "Rhode Island": "ロードアイランド州",
    "South Carolina": "サウスカロライナ州",
    "South Dakota": "サウスダコタ州",
    "Tennessee": "テネシー州",
    "Texas": "テキサス州",
    "Utah": "ユタ州",
    "Vermont": "バーモント州",
    "Virginia": "バージニア州",
    "Washington": "ワシントン州",
    "West Virginia": "ウェストバージニア州",
    "Wisconsin": "ウィスコンシン州",
    "Wyoming": "ワイオミング州",

    // カナダ主要州
    "Ontario": "オンタリオ州",
    "Quebec": "ケベック州",
    "British Columbia": "ブリティッシュコロンビア州",
    "Alberta": "アルバータ州",
    "Manitoba": "マニトバ州",

    // イギリス主要地域
    "England": "イングランド",
    "Scotland": "スコットランド",
    "Wales": "ウェールズ",
    "Northern Ireland": "北アイルランド",

    // オーストラリア主要州
    "New South Wales": "ニューサウスウェールズ州",
    "Victoria": "ビクトリア州",
    "Queensland": "クイーンズランド州",
    "Western Australia": "西オーストラリア州",
    "South Australia": "南オーストラリア州",

    // ドイツ主要州
    "Bavaria": "バイエルン州",
    "Berlin": "ベルリン州",
    "Hamburg": "ハンブルク州",
    "Hesse": "ヘッセン州",

    // フランス主要地域
    "Île-de-France": "イル＝ド＝フランス",
    "Provence-Alpes-Côte d'Azur": "プロヴァンス＝アルプ＝コート・ダジュール",
    "Auvergne-Rhône-Alpes": "オーヴェルニュ＝ローヌ＝アルプ",

    // その他海外主要地域
    "Madrid": "マドリード州",
    "Catalonia": "カタルーニャ州",
    "Lombardy": "ロンバルディア州",
    "Maharashtra": "マハラシュトラ州",
    "New Delhi": "ニューデリー特別首都圏",
    "Beijing": "北京市",
    "Shanghai": "上海市",
    "Seoul": "ソウル特別市",
    "Bangkok": "バンコク都",
    "Singapore": "シンガポール",
    "Jakarta": "ジャカルタ特別州",
    "Dubai": "ドバイ首長国",
    "Istanbul": "イスタンブール州",
    "Moscow": "モスクワ州",
    "Saint Petersburg": "サンクトペテルブルク州"
};
